import { Lead } from './types';

export const LEADS_DATA: Lead[] = [
  {
    id: '1',
    name: 'Nguyễn Văn Hùng',
    subInfo: 'BĐS nghỉ dưỡng',
    initials: 'NH',
    phone: '090 123 4567',
    email: 'hung.nguyen@gmail.com',
    address: '123 Võ Văn Kiệt',
    source: 'Facebook Ads',
    campaign: 'Sea Breeze Coastal 2024',
    status: 'Waiting',
    taxCode: '0314567890',
    avatarColorClass: 'bg-blue-100 dark:bg-blue-900/40 text-blue-600 dark:text-blue-300',
    
    birthDate: '1985-05-20',
    detailedIndustry: 'Kinh doanh Bất động sản',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    paymentTerms: 'Thanh toán 30 ngày',
    tradeName: 'Công ty TNHH Hùng Phát',
    supervisor: 'Lê Thanh Tâm',
    salesStaff: 'Trần Văn A',
    debtStaff: 'Nguyễn Thị B',
    initialPotential: 'Cao',
    initialGeneralInfo: 'Khách hàng quan tâm dự án biển',
    repDescription: 'Nam, khoảng 40 tuổi, quyết đoán',
    keyIndustry: 'Bất động sản',
    subIndustry: 'Du lịch',
  },
  {
    id: '2',
    name: 'Trần Thị Lan',
    subInfo: 'Căn hộ Studio',
    initials: 'TL',
    phone: '091 555 7890',
    email: 'lan.tran@email.com',
    address: '456 Nguyễn Trãi',
    source: 'Google Search',
    campaign: 'Urban Living 2024',
    status: 'Waiting',
    taxCode: '8329482932',
    avatarColorClass: 'bg-purple-100 dark:bg-purple-900/40 text-purple-600 dark:text-purple-300',

    birthDate: '1992-08-15',
    detailedIndustry: 'Thiết kế nội thất',
    district: 'Quận 5',
    city: 'TP. Hồ Chí Minh',
    paymentTerms: 'COD',
    tradeName: 'Studio Lan Trần',
    supervisor: 'Lê Thanh Tâm',
    salesStaff: 'Phạm Văn C',
    debtStaff: 'Hoàng Thị D',
    initialPotential: 'Trung bình',
    initialGeneralInfo: 'Cần thuê văn phòng nhỏ',
    repDescription: 'Nữ, trẻ, phong cách hiện đại',
    keyIndustry: 'Nội thất',
    subIndustry: 'Trang trí',
  },
  {
    id: '3',
    name: 'Phạm Tuấn',
    subInfo: 'Đất nền tỉnh',
    initials: 'PT',
    phone: '098 888 2233',
    email: 'tuan.pham@company.vn',
    address: '789 Lê Duẩn',
    source: 'TikTok Ads',
    campaign: 'Green Valley Hill',
    status: 'Waiting',
    taxCode: '1230984567',
    avatarColorClass: 'bg-orange-100 dark:bg-orange-900/40 text-orange-600 dark:text-orange-300',

    birthDate: '1978-12-01',
    detailedIndustry: 'Đầu tư tài chính',
    district: 'Hải Châu',
    city: 'Đà Nẵng',
    paymentTerms: 'Trả trước 50%',
    tradeName: 'Tuấn Investment',
    supervisor: 'Trần Minh Tuấn',
    salesStaff: 'Ngô Văn E',
    debtStaff: 'Lê Thị F',
    initialPotential: 'Rất cao',
    initialGeneralInfo: 'Tìm đất nền đầu tư dài hạn',
    repDescription: 'Nam, cẩn trọng, hỏi chi tiết',
    keyIndustry: 'Tài chính',
    subIndustry: 'Đầu tư',
  },
  {
    id: '4',
    name: 'Minh Anh',
    subInfo: 'Penthouse',
    initials: 'MA',
    phone: '092 111 4455',
    email: 'minh.anh@luxury.com',
    address: 'Landmark 81',
    source: 'Zalo Official',
    campaign: 'Sky High Luxury',
    status: 'Waiting',
    taxCode: '5556667778',
    avatarColorClass: 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-600 dark:text-emerald-300',

    birthDate: '1995-02-14',
    detailedIndustry: 'Thời trang cao cấp',
    district: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    paymentTerms: 'Thanh toán ngay',
    tradeName: 'Minh Anh Boutique',
    supervisor: 'Nguyễn Thanh Hương',
    salesStaff: 'Vũ Văn G',
    debtStaff: 'Đinh Thị H',
    initialPotential: 'Cao',
    initialGeneralInfo: 'Quan tâm căn hộ cao cấp nhất',
    repDescription: 'Nữ, sang trọng, quyết định nhanh',
    keyIndustry: 'Thời trang',
    subIndustry: 'Bán lẻ',
  },
];